version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: sc-nginx
    restart: always
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf.d
      - ./dist:/usr/share/nginx/html/springcloud-admin
      - ./show_nrrd_dist:/usr/share/nginx/html/show_nrrd_dist
    networks:
      - docker-compose_sc-net
    ports:
      - 9527:9527
      - 9528:9528

networks:
  docker-compose_sc-net:
    external: true
